# Generated by Django 2.1.13 on 2019-11-24 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sql', '0002_auto_20191124_1708'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='Images',
        ),
    ]
