# Generated by Django 2.1.13 on 2019-11-24 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sql', '0003_auto_20191124_1724'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='sql.Person')),
                ('image', models.ImageField(upload_to='images/')),
            ],
            options={
                'db_table': 'Image',
            },
        ),
        migrations.RemoveField(
            model_name='images',
            name='id',
        ),
        migrations.DeleteModel(
            name='Images',
        ),
    ]
