# Generated by Django 2.1.13 on 2019-11-24 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sql', '0004_auto_20191124_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='positionid',
            field=models.OneToOneField(db_column='positionId', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='sql.Person'),
        ),
    ]
